/// <reference types="cypress" />
const { getMaxListeners } = require("process")
const { createEmitAndSemanticDiagnosticsBuilderProgram } = require("typescript")
describe('admin user', () => {
    beforeEach(() => {
      cy.visit('http://cultureindahouse.westeurope.cloudapp.azure.com/')
      cy.get(".mdi-account-circle-outline").click()
      cy.contains("Correo").parent().type("admin1@fakemail.com")
      cy.contains("Contraseña").parent().type("admin")
      cy.get("[type=submit]").click()
      cy.contains("Bienvenido admin1 mylastname")
      Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      })
    })
    it('add category', ()=>{
        cy.contains("Añadir categoría").click()
        cy.contains("Nombre").parent().type("Ejemplo")
        cy.contains("Descripción").parent().type("Esto es un ejemplo")
        cy.get("span.v-btn__content").contains("C").click()
        //Comprobamos que en el desplegable de categoría del buscador está la opción añadida
        cy.wait(2000)
        cy.contains("Filtrar").parent().click()
        cy.get(".v-menu__content").contains("Ejemplo")
    })
    it('add Event', ()=>{
        cy.contains("Añadir evento").click()
        cy.contains("Nombre").parent().type("Ejemplo")
        cy.contains("Descripción").parent().type("Esto es un ejemplo")
        cy.contains("Precio").parent().type("20")
        cy.contains("Capacidad").parent().type("500")
        cy.contains("Duración").parent().type("02:00")
        cy.contains("Fecha").parent().type("2023-01-22")
        cy.contains("Categoría").parent().click()
        cy.contains("Ejemplo").click()
        cy.get("[type=file]").selectFile("C:/Users/cenoz/OneDrive/Escritorio/ejemplo.png", { force: true })
        cy.get("span.v-btn__content").contains("C").click()
        cy.wait(2000)
        cy.contains("Ejemplo")
    })
    it('add Company', ()=>{
        cy.contains("Gestionar empresa").click()
        cy.contains("+").click()
        cy.contains("Nombre").parent().type("Ejemplo")
        cy.contains("Descripción").parent().type("Esto es un ejemplo")
        cy.get("[type=file]").selectFile("C:/Users/cenoz/OneDrive/Escritorio/ejemplo.png", { force: true })
        cy.get("span.v-btn__content").contains("C").click()
        cy.contains("Gestionar empresa").click()
        cy.contains("Ejemplo")
    })
    it('mod Company', ()=>{
        cy.wait(2000)
        cy.contains("Gestionar empresa").click()
        cy.get(".mdi-puzzle-edit").last().click()
        cy.get(".v-text-field__slot").first().type("Nombre")
        cy.get("span.v-btn__content").contains("M").click()
        cy.wait(500)
        cy.contains("Gestionar empresa").click()
        cy.contains("Nombre")
    })
    it('assign business user', ()=>{
        cy.contains("Gestionar empresa").click()
        cy.contains("Nombre").parent().contains("Asignar").parent().click()
        cy.contains("business2").click()
        cy.contains("Nombre").parent().find(".mdi-account-check").click()
        cy.wait(500)
        cy.contains("Gestionar empresa").click()
        cy.contains("business2")
    })
    it('delete company', ()=>{
        cy.contains("Gestionar empresa").click()
        cy.contains("Nombre").parent().find(".mdi-delete").click()
        cy.wait(500)
        cy.contains("Gestionar empresa").click()
        cy.get('.pa-4').should('have.length', 1)
    })
    it('logout', ()=>{
        cy.get(".mdi-logout").click()
    })
})